// english translations for the app specific part

var MSG = {
    buttonRun: "Run",
    buttonStop: "Stop!",
    buttonConnect: "Connect",
    stateDisconnected: "disconnected",
    stateConnected: "connected",
    stateConnecting: "connecting...",
    stateRunning: "running...",
    stateProgramEnded: "ended",

    confirm_delete: "Really delete the entire program '%1'?",
    delete_not_connected: "The TXT has to be connected to be able to delete the entire program",

    // the menu
    dropdown_new: "New",
    dropdown_del: "Delete",

    // the skill system
    skillToolTip: "Select skill level '%1'",
    skill1: "beginner",
    skill2: "junior",
    skill3: "advanced",
    skill4: "senior",
    skill5: "expert",

    // blocks
    blockStartToolTip: "Program execution starts here",
    blockStartToolTipUnsaved: "\n(the program has not been saved yet)",

    blockWaitMessage: "wait %1 seconds",
    blockWaitToolTip: "Pause program execution a given time",
    blockRepeatMessage: "repeat %1 %2",
    blockRepeatToolTip: "Repeat something forever",
    blockPwmValueMessage: "%1",
    blockPwmValueToolTip: "Variable output state",
    blockOnOffMessage: "%1",
    blockOnOffToolTip: "On/off output state",
    
    blockMobileDriveMessage: "drive %1 %2 cm",
    blockForward: "forward",
    blockBackward: "backward",
    blockMobileDriveToolTip: "Drive a straight line of a given distance",
    blockMobileTurnMessage: "turn %1 %2",
    blockMobileTurnToolTip: "Turn in place",
    blockMobileConfigMessage: "Mobile robot configuration %1 Motors %2 and %3 of type: %4 Drive gear %5 : %6 %7 Wheel diameter: %8 cm %9 Wheel distance: %10 cm",
    blockMobileConfigToolTip: "User defined mobile robot configuration. Not needed for Discovery Set",
    blockMobileDriveWhileMessage: "drive %1 %2 %3",
    blockMobileDriveWhileToolTip: "Drive a straight line until something happens",
    blockWhile: "while",
    blockUntil: "until",

    blockOn: "on",
    blockOff: "off",
    
    blockAngleMessage: "%1",
    blockAngleToolTip: "Rotation value",
    blockRot45: "a little bit",
    blockRot90: "halfway",
    blockRot135: "much",
    blockRot180: "all around",

    blockIOSyncMessage: "simultaneously %1 %2",
    blockIOSyncToolTip: "Do output commands simultaneously",

    blockInputModeVoltage: "voltage in mV",
    blockInputModeSwitch: "switch state",
    blockInputModeResistor: "resistance",
    blockInputModeResistor2: "resistance 2",
    blockInputModeUltrasonic: "distance in cm",
    blockInputModeAnalog: "analogue",
    blockInputModeDigital: "digital",
    
    blockInputMessage: "%1 at input %2",
    blockInputToolTip: "Get a value from an input",

    blockInputConvTempMessage: "temperature %1 %2",
    blockInputConvTempToolTip: "Convert resistance into temperature",

    blockSimpleInputMessage: "input %1 is on",
    blockSimpleInputToolTip: "Read an input state",

    blockOutputModeOutput: "single outputs",
    blockOutputModeMotor: "motor output",
    
    blockOutputMessage: "set output %1 %2",
    blockOutputToolTip: "Set output state",
    
    blockMotorMessage: "start motor %1 turning %2 at %3",
    blockMotorToolTip: "Start a motor",
    blockLeft: "left",
    blockRight: "right",
    
    blockMotorStepsMessage: "start motor %1 turning %2 at %3 for %4 turns",
    blockMotorStepsToolTip: "Start a motor for a given number of turns",

    blockMotorSetMessage: "set motor %1 %2 to %3",
    blockMotorSetToolTip: "Set a motor value",
    blockMotorSetSpeed: 'speed',
    blockMotorSetDir: 'direction',
    blockMotorSetDist: 'distance',
    blockMotorSetGear: 'type',
    blockLeftRightMessage: "%1",
    blockLeftRightToolTip: "rotation left/right",
    blockGearMessage: "%1",
    blockGearToolTip: "encoder impulses per rotation",
    blockGearTXT: "new encoder motor (TXT)",
    blockGearTX: "old encoder motor (TX)",
    blockMotorSyncMessage: "link motors %1 and %2",
    blockMotorSyncToolTip: "Link two motors for synchronous operation",
    
    blockMotorHasStoppedMessage: "motor %1 has stopped",
    blockMotorHasStoppedToolTip: "Test if a motor has stopped",

    blockMotorOffMessage: "stop motor %1",
    blockMotorOffToolTip: "Stop a motor",

    blockJsPresentMessage: "joystick is connected",
    blockJsPresentToolTip: "Checks whether a joystick is connected to USB",
    blockJsAxisMessage: "joystick axis %1",
    blockJsAxisToolTip: "Read a joystick axis",
    blockJsButtonMessage: "joystick button %1 is pressed",
    blockJsButtonToolTip: "Read a joystick button",

    blockAxisX: "X",
    blockAxisY: "Y",
    blockAxisZ: "Z",
    blockAxisRx: "right X",
    blockAxisRy: "right Y",
    blockAxisRz: "right Z",
    blockAxisHx: "coolie hat X",
    blockAxisHy: "coolie hat Y",

    blockButtonTrigger:   "trigger",
    blockButtonThumb:     "thumb", 
    blockButtonThumb2:    "thumb2",
    blockButtonTop:       "top",
    blockButtonTop2:      "top 2",
    blockButtonPinkieBtn: "pinkie",
    blockButtonBaseBtn:   "base",
    blockButtonBaseBtn2:  "base 2", 
    blockButtonBaseBtn3:  "base 3",
    blockButtonBaseBtn4:  "base 4",
    blockButtonBaseBtn5:  "base 5",
    blockButtonBaseBtn6:  "base 6",
    blockButtonA:         "A",
    blockButtonB:         "B",
    blockButtonC:         "C",
    blockButtonX:         "X",
    blockButtonY:         "Y",
    blockButtonZ:         "Z",
    blockButtonTL:        "trigger left",
    blockButtonTR:        "trigger right",
    blockButtonTL2:       "trigger left 2",
    blockButtonTR2:       "trigger right 2",
    blockButtonSelect:    "select",
    blockButtonStart:     "start",
    blockButtonMode:      "mode",
    blockButtonThumbL:    "thumb left",
    blockButtonThimbR:    "thunb right",
    blockButtonDPadUp:    "direction up",
    blockButtonDPadDown:  "direction down",
    blockButtonDPadLeft:  "direction left",
    blockButtonDPadRight: "direction right",
    blockButtonOn:        "ir on",
    blockButtonOff:       "ir off",

    blockPlaySndMessage: "play sound %1",
    blockPlaySndToolTip: "Play a sound",
    blockSoundMessage: "%1",
    blockSoundToolTip: "Sound names",
    blockSoundAirplane: "Airplane",
    blockSoundAlarm: "Alarm",
    blockSoundBell: "Bell",
    blockSoundBraking: "Braking",
    blockSoundCar_horn_long: "Car horn long",
    blockSoundCar_horn_short: "Car horn short",
    blockSoundCrackling_wood: "Crackling wood",
    blockSoundExcavator: "Excavator",
    blockSoundFantasy_1: "Fantasy 1",
    blockSoundFantasy_2: "Fantasy 2",
    blockSoundFantasy_3: "Fantasy 3",
    blockSoundFantasy_4: "Fantasy 4",
    blockSoundFarm: "Farm",
    blockSoundFire_department: "Fire department",
    blockSoundFire_noises: "Fire noises",
    blockSoundFormula1: "Formula1",
    blockSoundHelicopter: "Helicopter",
    blockSoundHydraulic: "Hydraulic",
    blockSoundMotor_sound: "Motor sound",
    blockSoundMotor_starting: "Motor starting",
    blockSoundPropeller_airplane: "Propeller airplane",
    blockSoundRoller_coaster: "Roller coaster",
    blockSoundShips_horn: "Ships horn",
    blockSoundTractor: "Tractor",
    blockSoundTruck: "Truck",
    blockSoundRobby_1: "Robby 1",
    blockSoundRobby_2: "Robby 2",
    blockSoundRobby_3: "Robby 3",
    blockSoundRobby_4: "Robby 4",

    blockTextPrintColorMessage: "print in %1 %2",
    blockTextPrintColorToolTip: "Print the specified text in the given color",
    blockTextEraseMessage: "erase text",
    blockTextEraseToolTip: "Erase all text from screen",

    textVariable: "text",
    listVariable: "list",

    catCustom: "Custom",
    catInputs: "Inputs",
    catOutputs: "Outputs",
    catMotors: "Motors",
    catMobile: "Mobile",
    catLogic: "Logic",
    catLoops: "Loops",
    catMath: "Math",
    catText: "Text",
    catLists: "Lists",
    catVariables: "Variables",
    catFunctions: "Functions"
}
