// english translations for the app specific part

var MSG = {
    buttonRun: "Run...",
    buttonStop: "Stop!",
    stateDisconnected: "disconnected",
    stateConnected: "connected",
    stateConnecting: "connecting...",
    stateProgramEnded: "program ended",

    // blocks
    blockWaitMessage: "wait %1 seconds",
    blockWaitToolTip: "Pause program execution a given time",
    blockOnOffMessage: "%1",
    blockOn: "on",
    blockOff: "off",
    blockOnOffToolTip: "Input/output state",
    blockOutputMessage: "set output %1 %2",
    blockOutputToolTip: "Set output state on or off",
    blockInputMessage: "input %1 is on",
    blockInputToolTip: "Read an input state",
    blockPlaySndMessage: "play sound %1",
    blockPlaySndToolTip: "Play a sound",
    blockSoundMessage: "%1",
    blockSoundToolTip: "Sound names",
    blockSoundAirplane: "Airplane",
    blockSoundAlarm: "Alarm",
    blockSoundBell: "Bell",
    blockSoundBraking: "Braking",
    blockSoundCar_horn_long: "Car horn long",
    blockSoundCar_horn_short: "Car horn short",
    blockSoundCrackling_wood: "Crackling wood",
    blockSoundExcavator: "Excavator",
    blockSoundFantasy_1: "Fantasy 1",
    blockSoundFantasy_2: "Fantasy 2",
    blockSoundFantasy_3: "Fantasy 3",
    blockSoundFantasy_4: "Fantasy 4",
    blockSoundFarm: "Farm",
    blockSoundFire_department: "Fire department",
    blockSoundFire_noises: "Fire noises",
    blockSoundFormula1: "Formula1",
    blockSoundHelicopter: "Helicopter",
    blockSoundHydraulic: "Hydraulic",
    blockSoundMotor_sound: "Motor sound",
    blockSoundMotor_starting: "Motor starting",
    blockSoundPropeller_airplane: "Propeller airplane",
    blockSoundRoller_coaster: "Roller coaster",
    blockSoundShips_horn: "Ships horn",
    blockSoundTractor: "Tractor",
    blockSoundTruck: "Truck",
    blockSoundRobby_1: "Robby 1",
    blockSoundRobby_2: "Robby 2",
    blockSoundRobby_3: "Robby 3",
    blockSoundRobby_4: "Robby 4",

    catCustom: "Custom",
    catLogic: "Logic",
    catLoops: "Loops",
    catMath: "Math",
    catText: "Text",
    catVariables: "Variables",
    catFunctions: "Functions"
}
